### ISSUE TITLE
Plugin does not work in master branch with oauth.type=OAUTH

### ISSUE THREAD

**Issue by hundt** [davido/gerrit-oauth-provider#84] opened 2017-03-01 20:03 UTC
It appears that choosing this auth type means that Gerrit now expects a plugin to include an OAuthLoginProvider to be used for logging in. Since gerrit-oauth-provider does not include this, the plugin no longer works.

I was still able to get the plugin to work by using the OPENID_SSO auth type, but the plugin docs say not to do that so I'm concerned that it is not a good workaround.

edit: looking into it more, I guess the issue is that on the master branch of gerrit the logic in GitOverHttpModule.java is different: it sets `authFilter = ProjectOAuthFilter.class` whenever the auth type is OAUTH, whereas in the release branch it requires basic auth to be enabled as well. This was done in commit 84d830b5b350fdbae7c075473bceea9ec619b3c9

**Comment by davido** [comment] 2017-03-02 05:56
Do you mean that `git push` over OAuth2 protocoll doesn't work? This plugin in fact never supported this. Or you can't login? What is the error?

**Comment by davido** [comment] 2017-03-02 08:31
Fixed in: [1].

[1] https://gerrit-review.googlesource.com/98997

**Closed by davido** 2017-03-02 08:31 UTC
Labels: bug

**Comment by hundt** [comment] 2017-03-02 12:54
Yes, the problem was that gerrit wouldn't start. Sorry for the unclear report.

**Comment by davido** [comment] 2017-03-02 12:58
Thanks for the report. Should be fixed now. I will merge the fix in this repository, once it's accepted on Gerrit-review.

**Comment by hundt** [comment] 2017-03-02 13:20
Thanks!

**Comment by orian** [comment] 2017-10-25 11:20
I've setup gerrit 2.15-rc1 yesterday and added gerrit-oauth-provider.jar v2.14.3. It was throwing an error with `oauth.type=OAUTH`. Works fine with `OPENID_SSO` as described above.

**Comment by davido** [comment] 2017-10-25 13:27
> It was throwing an error with oauth.type=OAUTH

What error?

**Comment by orian** [comment] 2017-10-26 09:06
The exception from comment:
https://github.com/davido/gerrit-oauth-provider/issues/84#issuecomment-283564035

**Comment by davido** [comment] 2017-10-26 18:27
Are you sure it's exactly the same exception? The root cause was fixed. Can you paste the exception youe are seeing with latest plugin version? Can it be that you are using the old plugin version?

**Comment by paultung** [comment] 2017-11-03 09:29
I also got the same error in **Gerrit 2.4.15.1-1**, the plugin version I used is **2.14.3** got from:
https://github.com/davido/gerrit-oauth-provider/releases/tag/v2.14.3

The error message I got: _(same as @orian mention)_
```...(skip)
[2017-11-03 17:14:06,346] [main] INFO  com.google.gerrit.server.plugins.PluginLoader : Loaded plugin download-commands, version v2.14.5.1
[2017-11-03 17:14:06,452] [main] INFO  com.google.gerrit.server.plugins.PluginLoader : Loaded plugin gerrit-oauth-provider, version bcbc144
...(skip)
[2017-11-03 17:14:09,532] [main] ERROR com.google.gerrit.pgm.Daemon : Unable to start daemon
java.lang.IllegalStateException: Cannot start HTTP daemon
        at com.google.gerrit.pgm.http.jetty.JettyServer$Lifecycle.start(JettyServer.java:106)
        at com.google.gerrit.lifecycle.LifecycleManager.start(LifecycleManager.java:92)
        at com.google.gerrit.pgm.Daemon.start(Daemon.java:323)
        at com.google.gerrit.pgm.Daemon.run(Daemon.java:232)
        at com.google.gerrit.pgm.util.AbstractProgram.main(AbstractProgram.java:61)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.google.gerrit.launcher.GerritLauncher.invokeProgram(GerritLauncher.java:204)
        at com.google.gerrit.launcher.GerritLauncher.mainImpl(GerritLauncher.java:108)
        at com.google.gerrit.launcher.GerritLauncher.main(GerritLauncher.java:63)
        at Main.main(Main.java:24)
Caused by: javax.servlet.ServletException: No OAuth login provider installed
        at com.google.gerrit.httpd.ProjectOAuthFilter.pickOnlyProvider(ProjectOAuthFilter.java:196)
        at com.google.gerrit.httpd.ProjectOAuthFilter.init(ProjectOAuthFilter.java:100)
        at com.google.inject.servlet.FilterDefinition.init(FilterDefinition.java:111)
        at com.google.inject.servlet.ManagedFilterPipeline.initPipeline(ManagedFilterPipeline.java:99)
        at com.google.inject.servlet.GuiceFilter.init(GuiceFilter.java:226)
        at org.eclipse.jetty.servlet.FilterHolder.initialize(FilterHolder.java:139)
        at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:873)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:349)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:778)
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:262)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
        at org.eclipse.jetty.server.Server.start(Server.java:422)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
        at org.eclipse.jetty.server.Server.doStart(Server.java:389)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at com.google.gerrit.pgm.http.jetty.JettyServer$Lifecycle.start(JettyServer.java:92)
        ... 12 more
```

**Comment by mwebber** [comment] 2017-11-03 10:01
Can the folks who are getting the exception post the relevant part of their Gerrit config (masking any secrets, obviously)? I'm thinking that the `[auth]` section, and anything mentioning `oauth`.

**Comment by paultung** [comment] 2017-11-03 10:08
It's okay to me and here is my '_gerrit.config_':
```
[gerrit]
        basePath = git
        serverId = 4d7ad83a-f75d-40bb-9e69-35a05e880d08
        canonicalWebUrl = https://gerrit-devops.example.com:8080
[database]
        type = h2
        database = db/ReviewDB
[index]
        type = LUCENE
[auth]
        type = OAUTH
[sendemail]
        smtpServer = localhost
[sshd]
        listenAddress = *:29418
[httpd]
        listenUrl = https://*:8080/
        filterClass = com.googlesource.gerrit.plugins.ootb.FirstTimeRedirect
        firstTimeRedirectUrl = /login/%23%2F?account_id=1000000
[cache]
        directory = cache
[plugins]
        allowRemoteAdmin = true
[receive]
        enableSignedPush = false
[container]
        user = gerrit
        javaHome = /usr/java/jre1.8.0_152
[plugin "gerrit-oauth-provider-google-oauth"]
        client-id = 14236577659-xxxxxxxxxxxxxxxxxxxxxxpiqb.apps.googleusercontent.com
        fix-legacy-user-id = false
```

**Comment by davido** [comment] 2017-11-03 18:21
Ah right, the configuration is invalid. See this change and particularly
the default: [1] `auth.gitBasicAuthPolicy` is configured as:

```
By default this is set to `LDAP` when link:#auth.type[`auth.type`] is `LDAP`
and `OAUTH` when link:#auth.type[`auth.type`] is `OAUTH`.
Otherwise, the default value is `HTTP`.
```

So, that in case of `auth.type` == `OAUTH`, `auth.gitBasicAuthPolicy` is initialized to `OAUTH`. However the gerrit-provider-plugin currently doesn't implement that policy.

Solution: overload the plicy with HTTP:

```
[auth]
        type = OAUTH
        gitBasicAuthPolicy = HTTP
```

and this should fix it.

[1] https://gerrit-review.googlesource.com/#/c/gerrit/+/99079/5/Documentation/config-gerrit.txt@495

**Comment by paultung** [comment] 2017-11-06 01:49
Sorry reply late!

Yes!! That's my root cause, it fixed my problem and working fine now.

So sorry for my careless and many thanks for your great help!

**Comment by davido** [comment] 2017-11-08 13:13
> We should document it more prominently.

Done. I added documentation to https://github.com/davido/gerrit-oauth-provider/wiki/FAQ.
