### ISSUE TITLE
Sometimes I get "Not Found" on the login page

### ISSUE THREAD

**Issue by cermakcz** [davido/gerrit-oauth-provider#21] opened 2015-04-14 09:42 UTC
Not sure if this is actually caused by the plugin, but if I come to gerrit after some time and need to login again, I get "Not Found" text on the login page and the only way to get it working again is to delete cookies. There's usually just one, JSESSIONID.

**Comment by cermakcz** [comment] 2015-04-14 09:44
It also helps if whole Gerrit is restarted.

**Comment by tprochazka** [comment] 2015-04-14 10:35
+1

**Comment by davido** [comment] 2015-04-14 12:13
This was fixed in #5. Try release https://github.com/davido/gerrit-oauth-provider/releases/tag/v0.2.

**Comment by cermakcz** [comment] 2015-04-14 12:49
Thanks. So if I use the 0.2 plugin and the next release of Gerrit (when it's released), it should work fine, right?

**Comment by davido** [comment] 2015-04-14 12:58
Yes, But you don't need to wait until 2.10.3 is going to be released. I have built it with the needed patch included and uploaded release.war to https://github.com/davido/gerrit-oauth-provider/releases/tag/v0.2.

**Comment by davido** [comment] 2015-04-14 14:47
Closing as duplicate of #5.

**Closed by davido** 2015-04-14 14:47 UTC
Labels: duplicate
