### ISSUE TITLE
Incrementing Account Id at every login

### ISSUE THREAD

**Issue by EricHennigan** [davido/gerrit-oauth-provider#72] opened 2016-10-19 05:17 UTC
I've just installed the Release 2.13.1 using the gerrit-v2.13.1-10-gbf8b34a.war from https://github.com/davido/gerrit-oauth-provider/releases

Each time I "Sign In" through the google oauth process, I enter with an incremented Account Id, despite that it shows the same Email Address and Identity. The incrementing Account Id happens even when the oauth process has cached my google account. Unfortunately, with a new Account Id each time, I no longer have access to my previous configurations (such as projects, commit reviews, etc), nor can I regain my admin rights, as that requires recognizing me as Account Id 0.

**Comment by davido** [comment] 2016-10-19 05:32
Duplicate of https://github.com/davido/gerrit-oauth-provider/issues/69.

**Closed by davido** 2016-10-19 05:32 UTC
Labels: duplicate
