### ISSUE TITLE
OAuth login stop working after GerritAccount cookie expires

### ISSUE THREAD

**Issue by julienfromentc** [davido/gerrit-oauth-provider#5] opened 2015-03-26 12:45 UTC
Hello,

The Oauth login stops working when the GerritAccount cookie expires or is deleted. After clicking "Sign In", I am redirected to `http://gerrit.host/login/%23%2Fq%2Fstatus%3Aopen`, and the only thing shown on the page is `Not Found`

I am currently using both gerrit.war and gerrit-oauth-provider plugin that you have released on [Github] (https://github.com/davido/gerrit-oauth-provider/releases/tag/v0.1). I have configured the plugin to only  use Google OAuth provider.

Deleting the session cookie `JSESSIONID` "fixes" the issue.

Thanks

**Comment by sirivanleo** [comment] 2015-04-07 17:11
Hi,

My team is experiencing this issue on a daily basis, we have to clear our cookies in order to login, is there another more permanent work around or an intended fix for it?

I'm using gerrit 1.10.2 with the latest oauth plugin and only using oauth as a authentication.

-Leo

**Comment by OctoGerrit** [comment] 2015-04-08 14:59
Verified the JSEESIONID removal fixes the symptoms.  Still experiencing from latest pull and build.

**Comment by davido** [comment] 2015-04-12 08:45
Confirmed that the OAuth extension point is broken. There is a mismatch between web_sessions cache and OAuth session state. Fixed in [1].

The straight forward workaround for now is to increase the timeout (default is 12 hours), by adding something like that to the `gerrit.config`:

```
[cache "web_sessions"]
        maxAge = 1 month
```

[1] https://gerrit-review.googlesource.com/#/c/67040

**Comment by davido** [comment] 2015-04-12 11:54
https://github.com/davido/gerrit-oauth-provider/releases/tag/v0.2

**Closed by davido** 2015-04-12 11:54 UTC
Labels: bug
