### ISSUE TITLE
github auth doesn't populate email, nor does it allow adding them manually

### ISSUE THREAD

**Issue by finik** [davido/gerrit-oauth-provider#75] opened 2016-11-08 00:22 UTC
Or am I missing how to do that?
Had to add them manually on mysql DB directly.

**Comment by davido** [comment] 2016-11-08 06:34
It depends on wether a user exposes her email or not in his profile. In case she doesn't it cannot be retrieved and wouldn't be set. I think it should be possible to add it from the UI Is this a regression?

**Comment by finik** [comment] 2016-11-08 07:32
Not sure. It is a new gerrit instance I installed, this time with github oauth only. Email can not be added, link new identity reloads the page and does nothing either

**Comment by whoopsmith** [comment] 2017-05-10 19:24
I have the same problem.  New install of 2.13.6.  I have my email visible in my github profile but it does not show up in gerrit.  If I change my full name and then sign out/sign in then my name is updated but the email is still blank.  

I can't set it via ssh and set-account either.

Due to this I have to allow  Forge Author Identity or I can't submit any changesets

**Comment by davido** [comment] 2017-05-10 20:10
I am getting the email from the Rest endpoint and forwarding it to gerrit:

https://github.com/davido/gerrit-oauth-provider/blob/master/src/main/java/com/googlesource/gerrit/plugins/oauth/GitHubOAuthService.java#L108

@lucamilanesio: Does it work for you?

**Comment by whoopsmith** [comment] 2017-05-10 20:12
Is there some debugging I can enable to get a better idea of where it might be going wrong?

**Comment by davido** [comment] 2017-05-10 20:39
Sure, it is all there:

https://github.com/davido/gerrit-oauth-provider/blob/master/src/main/java/com/googlesource/gerrit/plugins/oauth/GitHubOAuthService.java#L92-L94

Try to add this line to your `gerrit.config` file:

```
[container]
        javaOptions = -Dlog4j.configuration=file:///home/gerrit/log4j.properties
```

And then extend the content of `log4j.properties` with something like this:

```
log4j.logger.com.googlesource.gerrit.plugins.oauth=DEBUG
```

Then it works here as expected:

```
[2017-05-10 22:38:02,803] DEBUG com.googlesource.gerrit.plugins.oauth.GoogleOAuthService : OAuth2: canonicalWebUrl=http://localhost:8080/
[2017-05-10 22:38:02,803] DEBUG com.googlesource.gerrit.plugins.oauth.GoogleOAuthService : OAuth2: scope=email profile
[2017-05-10 22:38:02,803] DEBUG com.googlesource.gerrit.plugins.oauth.GoogleOAuthService : OAuth2: domain=null
[2017-05-10 22:38:02,803] DEBUG com.googlesource.gerrit.plugins.oauth.GoogleOAuthService : OAuth2: useEmailAsUsername=false
[2017-05-10 22:38:08,133] DEBUG com.googlesource.gerrit.plugins.oauth.GitHubOAuthService : User info response: {"login":"davido","id":347173,"avatar_url":"https://avatars2.githubusercontent.com/u/347173?v=3","gravatar_id":"","url":"https://api.github.com/users/davido"
[...]
```

**Comment by whoopsmith** [comment] 2017-05-11 10:34
Where exactly is that log file supposed to be created and what is it going to be called?
 
I've think got that setup but I'm not sure its working.

I looked with logging ls-level and the closest thing I have is 
com.googlesource.gerrit.plugins.oauth.GitHubOAuthService which shows to be set to DEBUG.

But I don't see anything different in the ./logs directory and none of the files that are there seem to have any debug info in them.

**Comment by lucamilanesio** [comment] 2017-05-11 10:43
@whoopsmith could you post your help requests to the [Gerrit Mailing List](https://groups.google.com/forum/#!forum/repo-discuss)?

**Comment by whoopsmith** [comment] 2017-05-11 10:53
Will do.  Sorry to clutter the ticket.

**Comment by whoopsmith** [comment] 2017-05-11 16:05
Ok.  I have the debug output.

For anyone else not familiar with how debugging works you can enable this with

ssh <admin> gerrit logging set-level DEBUG com.googlesource.gerrit.plugins.oauth.GitHubOAuthService

So it looks like oauth-provider is working.  I can see my email in the output.
,"email":"smith@whoop.com",

So I guess this is a problem deeper in gerrit and I'll keep digging.  Any suggestions you might have on what to look at next would be helpful.  I know zero about gerrit internals.

**Comment by davido** [comment] 2017-05-11 19:20
What Gerrit version are you using? I have just rechecked again, on most recent master: 1fd6d4300c284a3691f8827f7fabdcf916b02acb. It worked as expected. I've created a new site from scratch and the first registered user got an email.

The easiest way to troublshoot this problem would be to set up dev environment (Bazel+Eclipse), build gerrit and plugin and debug it.

**Comment by davido** [comment] 2017-05-11 19:23
I saw in your comment to the dev ML, that you are using 2.13. This and older version were known to have some issue with account index. Only. 2.13.8 was known to work. Can you upgrade, or altertantively setup gerrit 2.13.8 from the scratch and see if your first user got correct email address?

**Comment by davido** [comment] 2017-05-11 19:36
This is where the emal is read from the OAuth provider rest endpoint result:

https://github.com/davido/gerrit-oauth-provider/blob/master/src/main/java/com/googlesource/gerrit/plugins/oauth/GitHubOAuthService.java#L102

This is the place where the email is written to the AuthRequest:

https://github.com/GerritCodeReview/gerrit/blob/stable-2.13/gerrit-oauth/src/main/java/com/google/gerrit/httpd/auth/oauth/OAuthSession.java#L145

This is the code, where the email is written in the backend:

https://github.com/GerritCodeReview/gerrit/blob/stable-2.13/gerrit-server/src/main/java/com/google/gerrit/server/account/AccountManager.java#L246-L252

**Comment by whoopsmith** [comment] 2017-05-11 20:34
Thank you for the 2.13.8 pointer.  I guess I never noticed there were updated releases after .6

I upgraded to 2.13.8 and it fixed everything.

**Comment by lucamilanesio** [comment] 2017-05-11 21:00
@whoopsmith you should follow the [Gerrit Mailing List](https://groups.google.com/forum/#!forum/repo-discuss)'s announcements and the social channels on [Twitter](http://twitter.com/gerritreview) and [Google+](https://plus.google.com/communities/111271594706618791655) 😺 instead of GitHub: this is only an copy of the master repository on [Gerrit Review](https://gerrit.googlesource.com/plugins/oauth)

**Comment by whoopsmith** [comment] 2017-05-11 21:09
Indeed.  I'm plugged in now on the Mailing list.  Hopefully won't miss them now.

I saw the 2.14 announcement and  was pondering a 2.14 upgrade but  I don't see an oauth yet marked ok for 2.14.

**Comment by lucamilanesio** [comment] 2017-05-11 21:12
What about [OAuth for Gerrit stable-2.14 branch](https://gerrit-ci.gerritforge.com/view/Plugins-stable-2.14/job/plugin-oauth-bazel-master-stable-2.14/lastSuccessfulBuild/artifact/bazel-genfiles/plugins/oauth/oauth.jar) ?

**Comment by whoopsmith** [comment] 2017-05-11 21:20
hmm.. ok. Well I guess still not plugged in enough yet. :)
  
I was looking in the All tab and there are entries for the previous versions but not 2.14.  I didn't think to also go look in the stable-2.14 tab.

Many thanks.  I'll try and upgrade tomorrow morning.

**Comment by davido** [comment] 2017-05-12 04:13
I'm closing it, as it works as expected in Gerrit older than 2.13 and later than 2.13.7.

**Closed by davido** 2017-05-12 04:13 UTC
