### ISSUE TITLE
Sign in not found

### ISSUE THREAD

**Issue by loboolsson** [davido/gerrit-oauth-provider#25] opened 2015-04-17 06:38 UTC
Around the 24 hour mark the sign in stops working. Clicking "Sign in" does not initialize a google login. It leads to the URL http://domain.com/login/%23%2Fq%2Fstatus%3Aopen and shows the message "Not Found" on screen. No error output is shown in error_log or httpd_log. The request itself with GET protocol, timestamp ip-address and so on is correcly logged in httpd_log but thats it

I have not configured a Github login.

A restart of gerrit (./gerrit.sh restart) solves the problem every time

**Comment by davido** [comment] 2015-04-17 08:15
Closing as duplicate of #5.

**Closed by davido** 2015-04-17 08:15 UTC
Labels: duplicate
